
version: '2'

services:
  angular2-frontend:
    image: angular2-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 5858:5858
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: node --debug=5858 app.js
